name: remote ssh command
on:
  push:
    branches: [main]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - name: Install Dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flask
      - name: Run tests
        run: pytest
  deploy:
    needs: run-tests
    runs-on: ubuntu-latest

    name: Lint Code Base
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
         
          fetch-depth: 0

     
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    
      - name: executing remote ssh commands using keys
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.MY_KEY }}
          port: ${{ secrets.PORT }}
          script: |
                  cd /home/winc/My-Proxy
                  git pull origin main